### ISSUE TITLE
Como lincar un issue a una request

### ISSUE THREAD

**Issue by sagatzt** [rosepernia/penpeople#8]
En la imagen que os dejo, tenéis la respuesta. Si linkais una issue a una request, cuando se haga el pullrequest, se podrá pasar automáticamente la issue a la columna de Done. El problema es que no lo habéis linkcado, tal y como nos parecía.

![Captura de pantalla de 2021-03-25 13-01-17](https://user-images.githubusercontent.com/57663900/112470226-b5bc5300-8d6a-11eb-9453-b7d498f36b08.png)

**Comment by rosepernia** [comment]
Genial, lo apuntamos. Muchas gracias :)
